# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Es buena practica agregar la version de python que utilizamos para el desarrollo
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      #- id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml

  # Pyupgrade convierte sintaxis antigua a una sintaxis moderna
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  # Django-upgrade para mantener actualizada la sintaxis del framework django
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.6.1" # replace with latest tag on GitHub
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"] # Replace with Django version

  # Formateador de codigo black
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  # DjHTML: A Template Formatter
  - repo: https://github.com/rtts/djhtml
    rev: "v1.5.0" # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2

  # ESlint para una mejor practica en archivos javascript, vue, jsx, etc.
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.14.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        args:
          - --fix #Bandera para corregir automaticamente los errores

  # Prettier formateador de codigo para archivos javascript, css, html, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        types_or: [css, javascript]
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"

  # Formatea documentacion al estilo de black cuando se encuentra codigo en dicha documentacion
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]

  # Isort ordena y agrupa las importaciones
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  # Flake8 es un linter que mejora las practicas al momento de escribir codigo, mas unos plgins que lo potencian
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1 # pick a git hash / tag to point to
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.4.25
          - flake8-no-pep420==2.2.0
          - flake8-comprehensions==3.8.0
