# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Es buena practica agregar la version de python que utilizamos para el desarrollo
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-json

  # Pyupgrade convierte sintaxis antigua a una sintaxis moderna
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  # Django-upgrade para mantener actualizada la sintaxis del framework django
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.22.1" # replace with latest tag on GitHub
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"] # Replace with Django version

  # Formateador de codigo black
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # DjHTML: A Template Formatter
  - repo: https://github.com/rtts/djhtml
    rev: "3.0.7" # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2

  # Prettier formateador de codigo para archivos javascript, css, html, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        types_or: [css, javascript]
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"

  # Formatea documentacion al estilo de black cuando se encuentra codigo en dicha documentacion
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]

  # Isort ordena y agrupa las importaciones
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  # Flake8 es un linter que mejora las practicas al momento de escribir codigo, mas unos plgins que lo potencian
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1 # pick a git hash / tag to point to
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.4.25
          - flake8-no-pep420==2.2.0
          - flake8-comprehensions==3.8.0
